project_id = "thwkmsuqkevfgqwlayqv"

[functions.newsletter-subscribe]
verify_jwt = false

[functions.newsletter-confirm]
verify_jwt = false

[functions.airtable-proxy]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-cart-checkout]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.cleanup-expired-cart]
verify_jwt = false
